/********************************************************************
* ./include/Dictionary_DmpEvtBgoMips.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoMips.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoMips();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoMips();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoMips();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoMips.h"
#include "DmpEvtBgoMips.h~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_string;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips;

/* STUB derived class for protected member access */
