//
// File generated by rootcint at Tue Oct 21 20:09:10 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIincludedIDictionary_DmpEvtBgoMips
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dictionary_DmpEvtBgoMips.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmpEvtBgoMips_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtBgoMips(void *p = 0);
   static void *newArray_DmpEvtBgoMips(Long_t size, void *p);
   static void delete_DmpEvtBgoMips(void *p);
   static void deleteArray_DmpEvtBgoMips(void *p);
   static void destruct_DmpEvtBgoMips(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtBgoMips*)
   {
      ::DmpEvtBgoMips *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtBgoMips >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtBgoMips", ::DmpEvtBgoMips::Class_Version(), "./include/DmpEvtBgoMips.h", 13,
                  typeid(::DmpEvtBgoMips), DefineBehavior(ptr, ptr),
                  &::DmpEvtBgoMips::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtBgoMips) );
      instance.SetNew(&new_DmpEvtBgoMips);
      instance.SetNewArray(&newArray_DmpEvtBgoMips);
      instance.SetDelete(&delete_DmpEvtBgoMips);
      instance.SetDeleteArray(&deleteArray_DmpEvtBgoMips);
      instance.SetDestructor(&destruct_DmpEvtBgoMips);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtBgoMips*)
   {
      return GenerateInitInstanceLocal((::DmpEvtBgoMips*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtBgoMips*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmpEvtBgoMips::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtBgoMips::Class_Name()
{
   return "DmpEvtBgoMips";
}

//______________________________________________________________________________
const char *DmpEvtBgoMips::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoMips*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtBgoMips::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoMips*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtBgoMips::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoMips*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtBgoMips::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoMips*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmpEvtBgoMips::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtBgoMips.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtBgoMips::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtBgoMips::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtBgoMips::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtBgoMips.
      TClass *R__cl = ::DmpEvtBgoMips::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "UsedFileName", (void*)&UsedFileName);
      R__insp.InspectMember("string", (void*)&UsedFileName, "UsedFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "StartTime", &StartTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "StopTime", &StopTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GlobalBarID", (void*)&GlobalBarID);
      R__insp.InspectMember("vector<short>", (void*)&GlobalBarID, "GlobalBarID.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BgoSide", (void*)&BgoSide);
      R__insp.InspectMember("vector<short>", (void*)&BgoSide, "BgoSide.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MPV", (void*)&MPV);
      R__insp.InspectMember("vector<double>", (void*)&MPV, "MPV.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Gsigma", (void*)&Gsigma);
      R__insp.InspectMember("vector<double>", (void*)&Gsigma, "Gsigma.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Lwidth", (void*)&Lwidth);
      R__insp.InspectMember("vector<double>", (void*)&Lwidth, "Lwidth.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MPV_Error", (void*)&MPV_Error);
      R__insp.InspectMember("vector<double>", (void*)&MPV_Error, "MPV_Error.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Gsigma_Error", (void*)&Gsigma_Error);
      R__insp.InspectMember("vector<double>", (void*)&Gsigma_Error, "Gsigma_Error.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Lwidth_Error", (void*)&Lwidth_Error);
      R__insp.InspectMember("vector<double>", (void*)&Lwidth_Error, "Lwidth_Error.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ChiS", (void*)&ChiS);
      R__insp.InspectMember("vector<double>", (void*)&ChiS, "ChiS.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtBgoMips(void *p) {
      return  p ? new(p) ::DmpEvtBgoMips : new ::DmpEvtBgoMips;
   }
   static void *newArray_DmpEvtBgoMips(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtBgoMips[nElements] : new ::DmpEvtBgoMips[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtBgoMips(void *p) {
      delete ((::DmpEvtBgoMips*)p);
   }
   static void deleteArray_DmpEvtBgoMips(void *p) {
      delete [] ((::DmpEvtBgoMips*)p);
   }
   static void destruct_DmpEvtBgoMips(void *p) {
      typedef ::DmpEvtBgoMips current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtBgoMips

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEshortgR_Dictionary();
   static void *new_vectorlEshortgR(void *p = 0);
   static void *newArray_vectorlEshortgR(Long_t size, void *p);
   static void delete_vectorlEshortgR(void *p);
   static void deleteArray_vectorlEshortgR(void *p);
   static void destruct_vectorlEshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<short>*)
   {
      vector<short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<short>", -2, "vector.dll", 0,
                  typeid(vector<short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<short>) );
      instance.SetNew(&new_vectorlEshortgR);
      instance.SetNewArray(&newArray_vectorlEshortgR);
      instance.SetDelete(&delete_vectorlEshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEshortgR);
      instance.SetDestructor(&destruct_vectorlEshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short> : new vector<short>;
   }
   static void *newArray_vectorlEshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short>[nElements] : new vector<short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEshortgR(void *p) {
      delete ((vector<short>*)p);
   }
   static void deleteArray_vectorlEshortgR(void *p) {
      delete [] ((vector<short>*)p);
   }
   static void destruct_vectorlEshortgR(void *p) {
      typedef vector<short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<short>

/********************************************************
* ./include/Dictionary_DmpEvtBgoMips.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtBgoMips();

extern "C" void G__set_cpp_environmentDictionary_DmpEvtBgoMips() {
  G__cpp_reset_tagtableDictionary_DmpEvtBgoMips();
}
#include <new>
extern "C" int G__cpp_dllrevDictionary_DmpEvtBgoMips() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmpEvtBgoMips */
static int G__Dictionary_DmpEvtBgoMips_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtBgoMips* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtBgoMips[n];
     } else {
       p = new((void*) gvp) DmpEvtBgoMips[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtBgoMips;
     } else {
       p = new((void*) gvp) DmpEvtBgoMips;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtBgoMips*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtBgoMips::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoMips::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtBgoMips::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtBgoMips::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtBgoMips*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoMips::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtBgoMips::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoMips::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoMips_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtBgoMips::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtBgoMips_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtBgoMips* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtBgoMips(*(DmpEvtBgoMips*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtBgoMips G__TDmpEvtBgoMips;
static int G__Dictionary_DmpEvtBgoMips_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtBgoMips*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtBgoMips*) (soff+(sizeof(DmpEvtBgoMips)*i)))->~G__TDmpEvtBgoMips();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtBgoMips*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtBgoMips*) (soff))->~G__TDmpEvtBgoMips();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtBgoMips_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtBgoMips* dest = (DmpEvtBgoMips*) G__getstructoffset();
   *dest = *(DmpEvtBgoMips*) libp->para[0].ref;
   const DmpEvtBgoMips& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmpEvtBgoMips */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDictionary_DmpEvtBgoMips {
 public:
  G__Sizep2memfuncDictionary_DmpEvtBgoMips(): p(&G__Sizep2memfuncDictionary_DmpEvtBgoMips::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDictionary_DmpEvtBgoMips::*p)();
};

size_t G__get_sizep2memfuncDictionary_DmpEvtBgoMips()
{
  G__Sizep2memfuncDictionary_DmpEvtBgoMips a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDictionary_DmpEvtBgoMips() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips))) {
     DmpEvtBgoMips *G__Lderived;
     G__Lderived=(DmpEvtBgoMips*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips),G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDictionary_DmpEvtBgoMips() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmpEvtBgoMips */
static void G__setup_memvarDmpEvtBgoMips(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips));
   { DmpEvtBgoMips *p; p=(DmpEvtBgoMips*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->UsedFileName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_string),-1,-1,1,"UsedFileName=",0,"file name of raw data");
   G__memvar_setup((void*)((long)(&p->StartTime)-(long)(p)),105,0,0,-1,-1,-1,1,"StartTime=",0,"the time of the first event used to cal. ped");
   G__memvar_setup((void*)((long)(&p->StopTime)-(long)(p)),105,0,0,-1,-1,-1,1,"StopTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GlobalBarID)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,1,"GlobalBarID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->BgoSide)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,1,"BgoSide=",0,"0,1 side and combined 2; ");
   G__memvar_setup((void*)((long)(&p->MPV)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"MPV=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Gsigma)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Gsigma=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Lwidth)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Lwidth=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MPV_Error)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"MPV_Error=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Gsigma_Error)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Gsigma_Error=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Lwidth_Error)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Lwidth_Error=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ChiS)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"ChiS=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDictionary_DmpEvtBgoMips() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmpEvtBgoMips(void) {
   /* DmpEvtBgoMips */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips));
   G__memfunc_setup("DmpEvtBgoMips",1281,G__Dictionary_DmpEvtBgoMips_168_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__Dictionary_DmpEvtBgoMips_168_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtBgoMips_168_0_3, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtBgoMips::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtBgoMips_168_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoMips::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtBgoMips_168_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtBgoMips::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtBgoMips_168_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtBgoMips::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtBgoMips_168_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtBgoMips_168_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoMips::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtBgoMips_168_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtBgoMips::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtBgoMips_168_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoMips::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtBgoMips_168_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtBgoMips::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtBgoMips", 1281, G__Dictionary_DmpEvtBgoMips_168_0_15, (int) ('i'), G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips), -1, 0, 1, 1, 1, 0, "u 'DmpEvtBgoMips' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtBgoMips", 1407, G__Dictionary_DmpEvtBgoMips_168_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtBgoMips_168_0_17, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips), -1, 1, 1, 1, 1, 0, "u 'DmpEvtBgoMips' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDictionary_DmpEvtBgoMips() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDictionary_DmpEvtBgoMips() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDictionary_DmpEvtBgoMips() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips = { "DmpEvtBgoMips" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtBgoMips() {
  G__Dictionary_DmpEvtBgoMipsLN_TClass.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_TBuffer.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_TMemberInspector.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_TObject.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_string.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDictionary_DmpEvtBgoMips() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_string);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoMipsLN_DmpEvtBgoMips),sizeof(DmpEvtBgoMips),-1,292096,(char*)NULL,G__setup_memvarDmpEvtBgoMips,G__setup_memfuncDmpEvtBgoMips);
}
extern "C" void G__cpp_setupDictionary_DmpEvtBgoMips(void) {
  G__check_setup_version(30051515,"G__cpp_setupDictionary_DmpEvtBgoMips()");
  G__set_cpp_environmentDictionary_DmpEvtBgoMips();
  G__cpp_setup_tagtableDictionary_DmpEvtBgoMips();

  G__cpp_setup_inheritanceDictionary_DmpEvtBgoMips();

  G__cpp_setup_typetableDictionary_DmpEvtBgoMips();

  G__cpp_setup_memvarDictionary_DmpEvtBgoMips();

  G__cpp_setup_memfuncDictionary_DmpEvtBgoMips();
  G__cpp_setup_globalDictionary_DmpEvtBgoMips();
  G__cpp_setup_funcDictionary_DmpEvtBgoMips();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary_DmpEvtBgoMips();
  return;
}
class G__cpp_setup_initDictionary_DmpEvtBgoMips {
  public:
    G__cpp_setup_initDictionary_DmpEvtBgoMips() { G__add_setup_func("Dictionary_DmpEvtBgoMips",(G__incsetup)(&G__cpp_setupDictionary_DmpEvtBgoMips)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDictionary_DmpEvtBgoMips() { G__remove_setup_func("Dictionary_DmpEvtBgoMips"); }
};
G__cpp_setup_initDictionary_DmpEvtBgoMips G__cpp_setup_initializerDictionary_DmpEvtBgoMips;

